version: "3.7"
services:
  app:
    build: ./nim
    tty: true
    volumes:
      - ../:/src
  db:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: dev
      TZ: Asia/Tokyo
    volumes:
      - ./mysql:/etc/mysql/conf.d
